apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: metadata
  namespace: quobyte
spec:
  template:
    metadata:
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: '/prometheus'
        prometheus.io/port: '7872'
      labels:
        role: metadata
        version: "2.0.pre4"
    spec:
      containers:
      - name: quobyte-metadata
        image: quay.io/quobyte/quobyte-server:2.0.pre4
        # imagePullPolicy: Always
        # resources:
        #   limits:
            # memory: "1212Mi"
            # cpu: "200m"

        # priviliged is required for full device inspector support
        securityContext:
          privileged: true
        env:
          - name: QUOBYTE_SERVICE
            value: metadata
          - name: QUOBYTE_REGISTRY
            value: registry
          - name: MAX_MEM
            valueFrom:
              configMapKeyRef:
                name: quobyte-config
                key: metadata.max_mem
          - name: MIN_MEM
            valueFrom:
              configMapKeyRef:
                name: quobyte-config
                key: metadata.min_mem
        command:
          - /bin/bash
          - -xec
          - |
            sed "s/.*MIN_MEM_METADATA=.*/MIN_MEM_METADATA=${MIN_MEM}/" -i /etc/default/quobyte
            sed "s/.*MAX_MEM_METADATA=.*/MAX_MEM_METADATA=${MAX_MEM}/" -i /etc/default/quobyte
            exec /bin/bash -x /opt/main.sh
        volumeMounts:
          - mountPath: /lib/modules
            name: lib-modules
          - mountPath: /mnt/quobyte
            name: mnt-quobyte
          - mountPath: /var/lib/quobyte
            name: var-lib-quobyte
            mountPropagation: Bidirectional
        ports:
          - name: rpc-tcp
            containerPort: 7872
            protocol: TCP
        readinessProbe:
          timeoutSeconds: 5
          httpGet:
            port: 7872
            path: /
        livenessProbe:
          initialDelaySeconds: 30
          timeoutSeconds: 5
          httpGet:
            port: 7872
            path: /
      nodeSelector:
        quobyte_metadata: "true"
      volumes:
        - name: lib-modules
          hostPath:
            path: /lib/modules
        - name: mnt-quobyte
          hostPath:
            path: /mnt/quobyte
        - name: var-lib-quobyte
          hostPath:
            path: /var/lib/quobyte
