apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: client
  namespace: quobyte
spec:
  template:
    metadata:
      labels:
        role: client
    spec:
      containers:
      - name: quobyte-client
        image: quay.io/sttts/quobyte-client-nsenter:1.2.10
        command:
          - /bin/sh
          - -xec
          - |
            ADDR=$(echo $(getent hosts ${QUOBYTE_REGISTRY} | awk '{print $1":7866"}') | tr ' ' ,)
            VOLUME=$(basename ${QUOBYTE_MOUNT_POINT})
            touch /rootfs/etc/fuse.conf
            if cut -d" " -f2 /etc/mtab | grep -q ${QUOBYTE_MOUNT_POINT}; then
              OPTS="-o remount"
            else
              mkdir -p ${QUOBYTE_MOUNT_POINT}
            fi
            /bin/nsenter --target=1 --wd=. --mount -- \
              lib/ld-linux-x86-64.so.2 --library-path ./lib \
              ./bin/mount.quobyte -f -d ${QUOBYTE_CLIENT_LOG_LEVEL} ${OPTS} ${ADDR}/${VOLUME} ${QUOBYTE_MOUNT_POINT}
        securityContext:
          privileged: true
        env:
          - name: QUOBYTE_CLIENT_HTTP_PORT
            value: "55000"
          - name: QUOBYTE_CLIENT_LOG_LEVEL
            value: INFO
          - name: QUOBYTE_REGISTRY
            value: registry
          - name: QUOBYTE_MOUNT_POINT
            value: /storage/cluster
        ports:
          - name: http-port
            containerPort: 55000
            hostPort: 55000
            protocol: TCP
        volumeMounts:
          - name: storage
            mountPath: /storage
          - name: rootfs
            mountPath: /rootfs
        imagePullPolicy: Always
      hostPID: true
      volumes:
      - name: storage
        hostPath:
          path: /storage
      - name: rootfs
        hostPath:
          path: /
