apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: registry
  namespace: quobyte
spec:
  template:
    metadata:
      labels:
        role: registry
        version: 1.3.6
    spec:
      containers:
        - name: quobyte-registry
          image: quay.io/quobyte/quobyte-server:1.3.6
          securityContext:
            privileged: true
          env:
            - name: QUOBYTE_SERVICE
              value: registry
            - name: QUOBYTE_RPC_PORT
              value: "7866"
            - name: QUOBYTE_HTTP_PORT
              value: "7876"
            - name: QUOBYTE_REGISTRY
              value: registry
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: QUOBYTE_EXTRA_SERVICE_CONFIG
              value: >
                constants.automation.manage_registry_replicas=true
            - name: MAX_MEM
              valueFrom:
                configMapKeyRef:
                  name: quobyte-config
                  key: registry.max_mem
            - name: MIN_MEM
              valueFrom:
                configMapKeyRef:
                  name: quobyte-config
                  key: registry.min_mem
          ports:
            - name: rpc-tcp
              containerPort: 7866
              protocol: TCP
            - name: rpc-udp
              containerPort: 7866
              protocol: UDP
            - name: http
              containerPort: 7876
              protocol: TCP
          volumeMounts:
            - name: devices
              mountPath: /devices/dev1
          command:
            - /bin/bash
            - -xec
            - |
              sed "s/.*MIN_MEM_REGISTRY=.*/MIN_MEM_REGISTRY=${MIN_MEM}/" -i /etc/default/quobyte
              sed "s/.*MAX_MEM_REGISTRY=.*/MAX_MEM_REGISTRY=${MAX_MEM}/" -i /etc/default/quobyte
              if [ ! -f /devices/dev1/QUOBYTE_DEV_SETUP ]; then
                mkdir -p /devices/dev1
                cat > /devices/dev1/QUOBYTE_DEV_SETUP <<EOF
              device.serial=${POD_NAME}-$(uuidgen)
              device.model=Kubernetes-hostDir
              device.type=DIR_DEVICE
              EOF
                if [ $(nslookup ${QUOBYTE_REGISTRY} | grep -A10 -m1 -e 'Name:' | wc -l) == 0 ]; then
                  echo "device.bootstrap=true" >> /devices/dev1/QUOBYTE_DEV_SETUP
                fi
              fi

              exec /bin/bash -x /opt/main.sh
          resources:
            limits:
              memory: "512Mi"
              cpu: "100m"
          lifecycle:
            preStop:
              exec:
                command: ["/bin/bash", "-xc", "qmgmt -u api registry remove $(grep device.id= /devices/dev1/QUOBYTE_DEV_ID | cut -d= -f2)"]
          readinessProbe:
            timeoutSeconds: 5
            httpGet:
              port: 7876
              path: /
          livenessProbe:
            initialDelaySeconds: 30
            timeoutSeconds: 5
            httpGet:
              port: 7876
              path: /
      nodeSelector:
        quobyte_registry: "true"
      volumes:
      - name: devices
        hostPath:
          path: /mnt/registry
